### ISSUE TITLE
Custom UINavigationController for NavigationCoordinator.

### ISSUE THREAD

**Issue by spaluchiewicz** [quickbirdstudios/XCoordinator#101]
Is it possible to initialise `NavigationCoordinator` with custom `UINavigationController` or this can be only achieved by (re)implementing it?

**Comment by jessbowers** [comment]
I'm also having trouble with this. Things I tried:

- Overriding `generateRootViewController()` to return a custom class. The super sets the delegate of the UINavigationController to `self.animationDelegate`. However, the `animationDelegate` is a private property. So this cannot be done in the child Coordinator.

- Setting the rootViewController type, but this is controlled by the Transition type. The Transition type is hard coded in `NavigationCoordinator`.

- Just copying the NavigationCoordinator, with a custom Transition. Much of NavigationCoordinator's elements are private so it's a lot of copying, which feels like the wrong approach.

At the least, making the animationDelegate accessible seems like a good approach. At best, allowing subclasses to define a subclass of UINavigationController as the root class is best.

For now, i'm stuck, will be copying NavigationCoordinator

**Comment by pauljohanneskraft** [comment]
If you take a look at the implementation of NavigationCoordinator, you can see, that it mostly consists of convenience initializers and sets up the delegate of the rootViewController. While it is probably a good idea to make the animationDelegate property of NavigationCoordinator accessible for all users, you can also create your own NavigationAnimationDelegate object and set it as your rootViewController's delegate, if you want (Just keep in mind to hold a strong reference to the delegate somewhere). The animationDelegate property is currently not accessible to avoid confusion with the TabBarCoordinator.delegate property. 

For now, you can also add the following line to your overriden `generateRootViewController` method: `rootViewController.delegate = super.generateRootViewController().delegate` to have access to the animationDelegate property - this of course is not a perfect solution, since it creates a new UINavigationController, which is shortly afterwards deallocated again.

I'm not a big fan of enabling users to define a subclass of UINavigationController as the rootViewController-type of a NavigationCoordinator, since it creates unnecessarily complicated code for beginners and as above mentioned, NavigationCoordinator is not that big of a difference to a BaseCoordinator, so more advanced users can easily write that themselves.
