### ISSUE TITLE
Is it OK to call trigger inside a coordinator?

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#103]
Hello,

I don't know how to solve this problem.

I have 3 coordinators:
AppCoordinator
LoginCoordinator
DashboardCoordinator

The AppCoordinator is run by the app delegate
When running the app, if we have a user in userdefaults (or whatever), we present the dashboard coordinator, otherwise, we present the login coordinator.

Problem I have is this one:
In the login screen, I want to press a button and then that view controller and login coordinator are dismissed, at the same time, I want that the dashboard coordinator is presented. Ideally, I would like to present the dashboard coordinator, and behind that, I would like to dismiss the login controller and release the login coordinator.

How should I do that?
My idea is this: 

```
enum LoginRoute: Route {
    case login
    case dismiss
}

final class LoginCoordinator: NavigationCoordinator<LoginRoute> {

    weak var appCoordinator: AppCoordinator?

    init(appCoordinator: AppCoordinator, initialRoute: RouteType? = nil) {
        self.appCoordinator = appCoordinator
        super.init(initialRoute: initialRoute)
    }

    override func prepareTransition(for route: LoginRoute) -> NavigationTransition {
        switch route {
        case.login:
            var vc = LoginViewController.instantiateController()
            let model = LoginViewModel(coordinator: anyRouter)
            vc.bind(to: model)
            return .push(vc)
        case .dismiss:
        	self.appCoordinator.trigger(.dashboard) // This is not working
            return .dismiss()
        }
    }
}
```

But it is not working.
What is the proper way to do this?
Thanks a lot.

**Comment by iniko83** [comment]
It's a moment, where RxSwift shines ;)
`
enum LoginRoute: Route {
  case presentDashboard(onDidAppear: (() -> Void)?)
}

        // in coordinator
        switch route {
        case let .presentDashboard(completion):
            var vc = DashBoardController()
            if let onDidAppear = onDidAppear {
                let firstDidAppear = vc.rx.methodInvoked(#selector(viewWillAppear(_:)))
                    .voidValues()
                    .take(1)
                    .subscribe(onNext: { _ in onDidAppear() })
                    .disposed(by: disposeBag)
            }
`

**Comment by Ricardo1980** [comment]
@iniko83  thanks but I am not using rxswift and in your code, it appears you are not doing anything with onDidAppear variable.

@pauljohanneskraft Can you help me with this please? Basically, I cannot create a coordinator that controls 2 other coordinators properly. Can you check this small app I created as an example?
The app coordinator should present the dashboard coordinator and then close the login coordinator, but it is closing the dashboard, I don't understand the reason. Thanks a lot for your time.
[CoordinatorTest.zip](https://github.com/quickbirdstudios/XCoordinator/files/3314498/CoordinatorTest.zip)

**Comment by pauljohanneskraft** [comment]
@Ricardo1980 I'm not quite sure how this is supposed to work with UIKit, maybe you can elaborate? Did you test this setup in another app not using XCoordinator, where this is working?

Please have a look at the implementations of the individual presentations you are calling (see https://github.com/quickbirdstudios/XCoordinator/blob/master/XCoordinator/Classes/TransitionPerformer%2BTransition.swift, especially the difference between `present` and `presentOnRoot` / `dismiss` and `dismissToRoot`). Make sure to first think which methods should be called in what order on which viewControllers - then check which transition fits best (since XCoordinator transitions mostly wrap UIKit method calls). If you need more control, take a look at `Transition.init(presentables:animationInUse:perform:)` where you can directly access the rootViewController and execute whichever method you'd like.

PS: I also noticed that you use `DispatchQueue.main.asyncAfter(...)` to execute code after a transition, you may want to have a look at the completion handler of the `trigger` method instead.

**Comment by pauljohanneskraft** [comment]
Not sure, if that helps you, but the following adaption first dismisses the loginCoordinator, then presents the dashboard. However, it shortly shows a black screen as it is showing the AppCoordinator's rootViewController, maybe you can tweak the animations and the AppCoordinator.rootViewController's appearance to make this work?

```
override func prepareTransition(for route: AppRoute) -> NavigationTransition {
        switch route {
        case .login:

            let showDashboardCoordinator: (() -> Void) = { [weak self] in
                print("--opening the dashboard coordinator and closing the login coordinator")
                self?.loginCoordinator?.trigger(.dismiss) {
                    self?.trigger(.dashboard)
                }
            }
            
            loginCoordinator = LoginCoordinator(showDashboardCoordinator: showDashboardCoordinator, initialRoute: .login)
            return .present(loginCoordinator!)

        case .dashboard:
            let dashboardCoordinator = DashboardCoordinator(initialRoute: .dashboard)
            return .present(dashboardCoordinator)
        }
    }
```

**Comment by Ricardo1980** [comment]
Hello, I will check what you said. Meanwhile, I want that the root view controller presents a navigation controller, then, later, another navigation controller is presented from the root view controller and the first navigation controller is then released.
What I am trying to solve is the problem of loading a lot of unnecesary view controllers in memory, a common example is login and dashboard. When you present the dashboard, we don't want the login behind anymore. How can I solve that? Thanks.

**Comment by pauljohanneskraft** [comment]
@Ricardo1980 How are you solving such a problem at the moment in other apps, where you want to achieve this? Like which methods/segues or whatever you are using there are executed in what order?

**Comment by Ricardo1980** [comment]
In a similar way to the code I attached.
The only difference is that I dismiss the first navigation controller in the presentation completion block of the second navigation view controller, and works fine.

**Comment by pauljohanneskraft** [comment]
@Ricardo1980 Can you send me an example of this?

**Comment by pauljohanneskraft** [comment]
I tried reworking your approach and it did not work (doing nothing) and printed the following output:

```
2019-06-21 16:27:46.363760+0200 CoordinatorTest[14005:146252] Warning: Attempt to present <UINavigationController: 0x7fe74f813200> on <UINavigationController: 0x7fe74e80e200> whose view is not in the window hierarchy!
```
This means that the AppCoordinator's rootViewController is not in the view hierarchy, since it is presenting the LoginCoordinator's rootViewController, which makes sense.

What I tried is the following:
```swift
case .dashboard:
   let coordinator = DashboardCoordinator(initialRoute: .dashboard)
    rootViewController.present(coordinator.rootViewController, animated: true) {
        self.loginCoordinator?.rootViewController.dismiss(animated: true, completion: nil)
    }
    return .none()
```

**Comment by Ricardo1980** [comment]
I am creating another example, I upload it as soon as I have it!

**Comment by Ricardo1980** [comment]
@pauljohanneskraft 
OK, I tried to do it without your library and I receive exactly the error you described. It seems you are right.
Checking an old app I created ages ago, I see that to achieve this properly, it is not using present first/dismiss second, but addChildViewController, apply animation, removeFromParentViewController and everything is released properly. I didn't remember that, but I was completely sure the memory management was done perfectly.

So, is this technically possible with your library?
In the worse case scenario, can I use dismiss and present, both without any kind of animation? I prefer that rather than a memory problem or watching a strange black background.

In my current scenario it is really important to release completely the previous coordinator/viewcontrollers/viewmodes, because they use web sockets and I have to release everything, including that network connection. That's why I need a proper AppCoordinator that, well, coordinates.

Thank you very much for your ideas.

**Comment by pauljohanneskraft** [comment]
Yes, but it requires a bit more work (not much, it's just not fully provided by default). You can create custom transitions using `Transition.init(presentables:animationInUse:perform:)` (You can read the documentation for this method for more information about what to specify when calling this initializer). To keep a similar style as used for the default transitions, you can wrap this into static functions on Transition. To concatenate different transitions together, have a look at `Coordinator.chain(routes:)`, `Transition.multiple` and `Coordinator.deepLink`.

Worst-case scenario (present/dismiss without animation): You can simply specify to not animated the routes being triggered:

```swift
let showDashboardCoordinator: (() -> Void) = { [weak self] in
    print("--opening the dashboard coordinator and closing the login coordinator")
    self?.loginCoordinator?.trigger(.dismiss, with: TransitionOptions(animated: false)) {
        self?.trigger(.dashboard, with: TransitionOptions(animated: false))
    }
}
```

Another idea in general would be to have an AppCoordinator as a separate class without rootViewController (not a Coordinator at all), which holds a reference to the window and sets its rootViewController. Since at the moment the AppCoordinator has an empty UINavigationController which is not really used at all - just an idea.

**Comment by pauljohanneskraft** [comment]
I assume that this issue is hereby resolved - if you have follow-up questions, feel free to reopen or write additional comments.

**Comment by Ricardo1980** [comment]
Yes, thanks a lot for your time. I am going to try what you said. Thanks!

**Comment by elishaterada** [comment]
@pauljohanneskraft @Ricardo1980 thank you for this conversation, I was struggling to create a smooth transition in the following scenarios without leaving unnecessary views in memory:

- login -> dashboard
- dashboard -> login
- some view -> app suspended -> user triggers home shortcut action -> some deep link

I got most of the way except the black blank screen on root... until I found this conversation. Thank you, I love to see more of these techniques surfaced in the doc and example (unless I missed it)!

**Comment by Ricardo1980** [comment]
@elishaterada can you explain to us the approach you selected?
Thanks :)

**Comment by elishaterada** [comment]
Basically used this part in conjunction with notification pattern so that child view controller can dispatch an event that triggers AppRoute level route change.

```
    self?.loginCoordinator?.trigger(.dismiss, with: TransitionOptions(animated: false)) {
        self?.trigger(.dashboard, with: TransitionOptions(animated: false))
    }
```
