### ISSUE TITLE
Memory cycle

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#115]
Hello,

@pauljohanneskraft 
I am trying to implement this idea:
"Another idea in general would be to have an AppCoordinator as a separate class without rootViewController (not a Coordinator at all), which holds a reference to the window and sets its rootViewController. Since at the moment the AppCoordinator has an empty UINavigationController which is not really used at all - just an idea."
https://github.com/quickbirdstudios/XCoordinator/issues/103

I see a memory cycle and I don't know how to fix it.
Can you help me?

Basically, I have a Login coordinator using XCoordinator and another AppCoordinator that does not use XCoordinator, I just use the AppCoordinator to replace coordinators and solve UIKit limitations and solve memory problems.
But I have another memory problem.
It seems that the Login coordinator retains the view controller/viewmodel, which is retained by the UINavigationController in the coordinator, however, it appears that the view model is retaining the coordinator, creating a cycle, so, it is impossible to release the Login coordinator, login view controller and login view model.
I checked that with Instruments (allocations instrument) and The Visual Memory Debugger and I see this problem clearly.
Can you help me with this problem?
If I declare weak or unowned the router inside the view model to try to avoid the cycle, the app crashes.
Can you see where the problem is?
Thanks a lot for your help.

[CoordinatorTestSample.zip](https://github.com/quickbirdstudios/XCoordinator/files/3428069/CoordinatorTestSample.zip)

After moving to another VC, the login is still there.
![Uploading Screenshot 2019-07-24 at 18.01.50.png…]()

**Comment by pauljohanneskraft** [comment]
The router is a type-erased version (separate class with closures for the methods provided by the Router protocol), so declaring an AnyRouter as weak will most likely fail since you are not holding the coordinator weakly, but the wrapper around it.

For the problem you described, I first want to describe what I did, continue with what I found out and conclude with possible fixes:

What I did:
- I built & ran your project
- I tapped on the only available button
- I tapped on the memory debugger

What I found out:
- The rootViewController of the AppCoordinator is still strongly holding its rootViewController after it has been added to the view hierarchy, which should not be the case. The next major version of XCoordinator will handle these references differently to make these types of errors less likely and the framework as a whole more intuitive.

Possible fixes:
- call `router.presented(from: rootViewController)` right after you added its rootViewController to the view hierarchy (i.e. at the end of the `start` method).

Since this fixed the problem in the example project, I'm closing the issue for now. Feel free to reopen, continue this thread or open additional issues, if necessary.
