### ISSUE TITLE
Multiple present transitions

### ISSUE THREAD

**Issue by msebgf** [quickbirdstudios/XCoordinator#116]
I have a navigation coordinator with 5 different views ( viewA, viewB, viewC, viewD, ViewE)

So the order of how I'm presenting the views is

push(viewA)
push(viewB)
present(viewC)
present(viewD)
present(viewE) -> Here I get a warning

Warning: Attempt to present "ViewE" on "ViewD" whose view is not in the window hierarchy!
So the ViewD is never presented.

**What am I doing wrong? Is there some sort of limit to how many views can I 'present'**

If I do:

push(viewA)
push(viewB)
push(viewC)
present(viewD)
present(viewE)

it works

**Comment by pauljohanneskraft** [comment]
Hey @msebgf, this looks like quite a difficult scenario, which we haven't encountered yet.

There are two different present transitions available in XCoordinator:
- `.present` presents on the currently presented viewController, if available otherwise on the rootViewController of that coordinator
- `.presentOnRoot` always presents on the rootViewController of the coordinator

Maybe you can try to switch some of your `.present` transitions to be `.presentOnRoot`? Would that work? Which types do your views have, are they all UIViewControllers and are they all presented using a modal transition or are also alerts/popovers involved?

**Comment by msebgf** [comment]
I've tried with `.presentOnRoot` as well, all of them are UIViewcontrollers, at the beginning viewE was supposed to be a UITabBarController, and my first guess what the tab bar was the problem, then I tried with a simple UIViewController, and the problem was still there

**Comment by pauljohanneskraft** [comment]
After checking the issue with an example project, I found the cause of this problem and fixed it in https://github.com/quickbirdstudios/XCoordinator/pull/117.
