### ISSUE TITLE
Can't run example project

### ISSUE THREAD

**Issue by alanpridestar** [quickbirdstudios/XCoordinator#120]
Hi, 

I can't seem to run the example project. I am using XCode 10.2.1, have cloned your project, opened the example project and am hit with this error when I am building:

![Screen Shot 2019-08-19 at 3 46 25 PM](https://user-images.githubusercontent.com/40860015/63266424-914beb00-c298-11e9-8450-4cddee7caf14.png)

I've tried re-adding the Pods, cleaning the project, changing the build settings, but constantly the same error. 

I am able to run it in my own app, so this issue doesn't really impede me much, but figured to submit an issue anyway.

Thanks, 
Alan

**Comment by pauljohanneskraft** [comment]
This seems to be connected with [this](https://github.com/quickbirdstudios/XCoordinator/issues/85) other issue. Please make sure to not have any whitespace in your path leading to the project, otherwise it will fail due to the shell invocation step for SwiftLint.

In case moving the project to another path without whitespace did not fix your problem, feel free to reopen or add additional comments.
