### ISSUE TITLE
XCoordinatorRx can't be built with Xcode 11

### ISSUE THREAD

**Issue by peacemoon** [quickbirdstudios/XCoordinator#127]
It looks like there is a problem to build `XCoordinatorRx` from Carthage

![Screenshot 2019-09-24 at 15 13 58](https://user-images.githubusercontent.com/478757/65514694-1b155680-dede-11e9-9f00-c88f6762ee1e.png)

**Comment by pauljohanneskraft** [comment]
Hey, thanks for catching that one! Apparently a simple `swift package generate-xcodeproj` fixes the problem...

**Comment by peacemoon** [comment]
<img width="1663" alt="Screenshot 2019-09-26 at 21 33 32" src="https://user-images.githubusercontent.com/478757/65719115-58781080-e0a5-11e9-9345-ca1d454391e2.png">

thank you the update, unfortunately the issues still persists with version 2.0.4 . I am using Xcode 11.1

**Comment by pauljohanneskraft** [comment]
I tried it yesterday with the most recent stable version of Xcode, so it might be a Xcode beta bug. Can you check it again with a stable version of Xcode? If you can reproduce it there, I will have a deeper look.

**Comment by peacemoon** [comment]
I'm using Xcode 11.1 GM Seed, not beta.
It is quite easy to reproduce, just create a Carfile with the following content:
````
github "quickbirdstudios/XCoordinator" ~> 2.0
````
and run
````
carthage update
`````
you will see the error.

I've just play around with the bug a little bit. I think the problem is that the source code of `RxSwift` are not checked out correctly. If I go to `Carthage/Checkouts/XCoordinator` and run `swift package update`, I can open `XCoordinator.xcodeproj` directly and compile `XCoordinatorRx` successfully.

I doubt that `Carthage` currently supports this kind of Swift Package Manager setup.

**Comment by pauljohanneskraft** [comment]
ok, for some reason, my latest tries also failed even though yesterday I somehow got it to build...

I dove a little deeper into the problem and now tried adding a `Build Script Phase` for running `swift package update`, which you can find on the branch `fix/carthage-xcode11`. It worked three times in a row for me, however since the last release of XCoordinator did not solve the problem, it would be nice, if you could confirm whether it works now or not. It failed once after adding the build phase when it built schemes in a different order, however I could no longer reproduce it later.

I ran 
```
rm Cartfile.resolved && rm -rf Carthage && carthage update --platform iOS
``` 
with a Cartfile only containing 
```
github "quickbirdstudios/XCoordinator" "fix/carthage-xcode11"
```

I really hope this solves the problem, since I'm not quite sure how to solve it otherwise. I also searched for similar problems and only found workarounds where `swift package generate-xcodeproj` is called manually at some point... Do you have any additional ideas on how to solve this?

**Comment by peacemoon** [comment]
```
Is there a way to force that order for Carthage?
```

I don't have any solution for this either.

Maybe it is also time to move to Swift Package Manager instead of using Carthage :)

**Comment by pauljohanneskraft** [comment]
I will try to provide binaries for the upcoming releases - however it is definitely a good idea to switch to SwiftPM. If there is more interest into fixing this issue for other users, feel free to contact me, since otherwise I would not pursue any further with fixing this issue.
