### ISSUE TITLE
Using a viewmodel in multiple coordinators/routers?

### ISSUE THREAD

**Issue by paulmeyerle** [quickbirdstudios/XCoordinator#148]
Since the Router/Coordinator has an associatedtype for the supported routes how should I go about including the same view/viewmodel in multiple coordinators?  Would I need to implement multiple viewmodels, for the same viewcontroller, just to handle the different route enums or is there a better way?

**Comment by pauljohanneskraft** [comment]
Hey @paulmeyerle,

there are the following options I could come up with:

### 1. Scene-specific route

By creating a separate route for that scene, you can have different coordinators for the individual use cases. If you encounter a flow, where you have other scenes interacting with it, you can inject a rootViewController, have parent and/or child coordinators, if necessary.

### 2. Creating a Route protocol

You can create a protocol for your route, which multiple route types conform to. An example for a LoginRoute could look like this with a following generic LoginViewModel:

```swift
protocol LoginRoute: Route {
    static func loginSuccessful() -> Self
    static func loginFailed() -> Self
}

class LoginViewModel<RouteType: LoginRoute> {
    var router: UnownedRouter<RouteType>
}
```

### 3. Creating different viewModels

Sometimes it might not make sense to combine behavior of viewModels used in different flows since they might deviate quite a lot over time. So, in some (maybe rare, but definitely existant) cases, it might make sense to either copy or share code of the two scenes instead of using the same viewModel.

### 4. Mocking unused transitions

If your viewModel is simply more restricted in one flow in comparison to another one, it might make sense to just "mock" the transitions by returning `Transition.none()` for the unused cases. Of course, you should still make this change in functionality visible to the user, but for a quick workaround or some special cases, this might also come in handy.

### 5. Creating a custom Router-protocol

You can also create a protocol for your router as in the following:

```swift
protocol LoginRouter: AnyObject {
    func loginSuccessful()
    func loginFailed()
}
```

For this, you will need to make sure, that you do not keep a strong reference from the viewModel to the router. And you will need to implement these methods similar to this:

```swift
extension Router where RouteType == LoginRoute {
    func loginSuccessful() {
        trigger(.loginSuccessful())
    }

    func loginFailed() {
        trigger(.loginFailed())
    }
}
```

I hope, this was helpful and that you could easily solve your problem. Let me know, if you found a better/different solution to add to the list or which one best fit your problem, since it might help others with a similar problem.

**Comment by pauljohanneskraft** [comment]
I'm closing this for now - if you have a better solution or follow-up questions, feel free to reopen, add additional comments or open new issues.
