### ISSUE TITLE
Present Modal then Push VC

### ISSUE THREAD

**Issue by AAAstorga** [quickbirdstudios/XCoordinator#153]
I am having a hard time figuring out how to present a modal and then push a view controller on that modal. 

To see what I am talking about, if you go to the App Store app, click on your profile, then click "Subscriptions", it pushes a new VC on the current modal. Do you have any guidance on how to do that?

Thank you so much!

**Comment by pauljohanneskraft** [comment]
Hey @AAAstorga,

There's multiple ways of approaching it, here's a rundown of your options:

1. **Wrap your modal into a NavigationCoordinator**

You can wrap your modal into a NavigationCoordinator, which pushes a viewController in an initial route or specifies a `root` presentable in the initializer. Since all transitions allow specification of a Presentable and not a strict UIViewController, you can present your coordinator instead of the modal viewController then.

2. **Use the `perform(_:on:)` transition**

To perform a transition on a viewController different from the rootViewController of the coordinator itself, you can call the `Transition.perform(_:on:)` transition. Example:

```swift
override func prepareTransition(for route: MyRoute) -> ViewTransition {
    switch route {
    case .someRoute:
        let viewController = SomeViewController()
        let navigationController = UINavigationController()
        return .multiple(
            .perform(NavigationTransition.push(viewController), on: navigationController),
            .present(navigationController)
        )
    }
}
```

You might also call the push transition well after the presentation of the navigationController by injecting the coordinator into the viewController/viewModel, which is part of the modal and storing the modally presented navigationController in the coordinator. This would however get quite complicated and I would then consider `Option 1` instead.

3. **Call `pushViewController` method on your own**

You can of course still call the push method as specified in the [UIKit documentation](https://developer.apple.com/documentation/uikit/uinavigationcontroller/1621887-pushviewcontroller).

### Conclusion

If you have a relatively plain modal without much going on, option 2 would not create too much overhead for simple cases. Once the modally presented viewController triggers its own routes, you might want to consider option 1. Option 3 is more of a last resort and should actually not be needed when writing your whole app using XCoordinator. In the App Store case, I would pick option 1 and introduce a `ProfileCoordinator: NavigationCoordinator<ProfileRoute>`, since there would be multiple tableView elements triggering different routes.

**Comment by AAAstorga** [comment]
@pauljohanneskraft Ah makes sense! I went for option 1 and it works great. I totally forgot I can use a Coordinator as a Presentable. Thanks for being super responsive. Loving the library so far 💯
