### ISSUE TITLE
Dismissal animation not working

### ISSUE THREAD

**Issue by francisbourquestudyo** [quickbirdstudios/XCoordinator#164]
Hi! I'm trying to implement a custom animation when present a view controller. However, the dismissal doesn't seem to be working. When doing this

```
let animation = Animation(presentation: ZoomInAnimation(), dismissal: ZoomOutAnimation())
return .present(vc, animation: animation)
```

the presentation animation works as expected but not the dismissal. I get the default animation.

**Comment by pauljohanneskraft** [comment]
Hey @francisbourquestudyo!

Since Animations are used as `transitioningDelegate` in your viewController and therefore are not held strongly by the viewController itself (but only as a weak reference), you will have to make sure to hold it yourself. What we like to do is defining a `static let` on Animation.

Example:

```swift
extension Animation {
    static let zoom = Animation(presentation: ZoomInAnimation(), dismissal: ZoomOutAnimation())
}
```

then you can write: `.present(vc, animation: .zoom)`.

**Comment by francisbourquestudyo** [comment]
Thanks! That solved it
