### ISSUE TITLE
Custom tabBar 

### ISSUE THREAD

**Issue by KareemAbdelSattar** [quickbirdstudios/XCoordinator#171]
i try a lot of times to change tab bar view in TabBarCoordinator but i can't to solve this problem 
and try to assign any tab bar pod to change the shape it is not work
please help

**Comment by pauljohanneskraft** [comment]
You can use a custom UITabBarController by specifying it in the initializer of a TabBarCoordinator. We are injecting a custom UITabBarControllerDelegate, but should only do so, if you specify none before. What you can also do is modifying properties of the `rootViewController` of the TabBarCoordinator, which is the UITabBarController used for the transitions of the UITabBarCoordinator.

Since you did not provide a lot of context of what you have tried and what specifically did not work, it would be nice, if you could provide said information, so that we can sort out the problem.

**Comment by pauljohanneskraft** [comment]
Closed due to inactivity - should the problem persist, feel free to open new issues or add further comments.
