### ISSUE TITLE
Question around completion block after a transition in Navigation Coordinator

### ISSUE THREAD

**Issue by anuragt84** [quickbirdstudios/XCoordinator#173]
In XCoordinators 2.0, I see that some of the code in `UINavigationController+Transition.swift` changed under the method `set(_ viewControllers....)` at https://github.com/quickbirdstudios/XCoordinator/blob/4b6fc6f7359078c322e3b354854ed4ac5c12c5e1/Sources/XCoordinator/UINavigationController%2BTransition.swift#L64

There is a new `autoreleasepool` around `setViewControllers` at https://github.com/quickbirdstudios/XCoordinator/blob/4b6fc6f7359078c322e3b354854ed4ac5c12c5e1/Sources/XCoordinator/UINavigationController%2BTransition.swift#L87

What was the reason for this? The reason I ask is, a thing I observed in XCoordinators in 1.0 is that when you trigger a route (with a completion block) on a Navigation Coordinator that sets a new set of View Controllers on the Navigation Controller, by the time the first line of the completion block is called, the old view controllers that were removed from the Navigation Controller's view controllers are still in memory.

**Comment by pauljohanneskraft** [comment]
I noticed a few of these problems and wanted to be sure that everything is released from memory... However, I'm not quite sure, whether that change gave any real benefit but since it also shouldn't do much harm either, I left it in...

Do you have any issue with the current version or with an earlier version and you are thinking whether that would solve your problem?

**Comment by pauljohanneskraft** [comment]
Closed due to inactivity - should the problem persist, feel free to open new issues or add further comments.
