### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by cilman** [quickbirdstudios/XCoordinator#189]
Hi, Im new to XCoordinator, im using it with viper and loved

I dont know where to ask questions so im writing here

1. How can i prevent default transition animation, for ex : return .pop() is animating but i dont want it.
2. How can i change default right to left transition animation to bottom to up, like we did it using standart VC push.

Thanks.

**Comment by pauljohanneskraft** [comment]
Hey - glad you like it 😊 

1. You can disable the transition when triggering a route, i.e. call `router.trigger(.someRoute, with: TransitionOptions(animated: false))` instead of just `router.trigger(.someRoute)`
2. You can specify an `Animation` object with most of the available transitions (e.g. `Transition.push`). Have a look at [this folder](https://github.com/quickbirdstudios/XCoordinator-Example/tree/master/XCoordinator-Example/Animations) for some examples and take a look at the code documentation - if you have any questions, feel free to comment here or open another issue.

**Comment by pzmudzinski** [comment]
@cilman I think API for passing options in `trigger(... on: ...)` is missing. You can add it by yourself:
```swift
extension Transition {
    public static func trigger<R: Router>(_ route: R.RouteType, on router: R, options: TransitionOptions) -> Transition {
        Transition(presentables: [], animationInUse: nil) { _, _, completion in
            router.trigger(route, with: options, completion: completion)
        }
    }
}
```
