### ISSUE TITLE
Trigger a NavigationCoordinator inside a Page Coordinator

### ISSUE THREAD

**Issue by Daniebro5** [quickbirdstudios/XCoordinator#200]
I'm trying to trigger a second coordinator as follows:

```enum 
StepsListRoute: Route {
  case otherCoordinator
}

class StepsPageCoordinator: PageCoordinator<StepsListRoute> {
  
  override func prepareTransition(for route: StepsListRoute) -> PageTransition {
    switch route {
    case .insuranceOptions:
      let coordinator = otherCoordinator(rootViewController: self.rootViewController)
      return .trigger(OtherRoute.some, on: coordinator)
    }
  }
}
```

But I'm seeing "Cannot convert value of type 'UIPageViewController' to expected argument type 'NavigationCoordinator<SomeRoute>.RootViewController' (aka 'UINavigationController')". What am I doing wrong?

**Comment by chefnobody** [comment]
If `.trigger(OtherRoute.some, on: coordinator)` does not return `PageTransition` type, you're probably going to get this error.

**Comment by pauljohanneskraft** [comment]
Hey @Daniebro5 !

In the line `let coordinator = otherCoordinator(rootViewController: self.rootViewController)`, you are trying to create a NavigationCoordinator (or a subclass thereof) with a rootViewController of `UIPageViewController` instead of `UINavigationController`. 

To give a little bit more context:

Each coordinator has a rootViewController it is managing. In the case of a PageCoordinator this is a UIPageViewController, for NavigationCoordinator this is a UINavigationController. When a route is triggered, a transition is created, which is then performed on this exact rootViewController. 

Since in your example code, you are trying to create a NavigationCoordinator with a UIPageViewController, the compiler is trying to tell you that not all of the UINavigationController capabilities are available for UIPageViewController (for example `pushViewController`).

In a normal case, you would probably simply initialize the NavigationCoordinator without specifying a rootViewController (it will simply create one itself then), or specify one - e.g. `let coordinator = otherCoordinator(rootViewController: UINavigationController())`
