### ISSUE TITLE
Crash when Creating Strong Router from Navigation Coordinator Defined in Framework

### ISSUE THREAD

**Issue by janakagamini** [quickbirdstudios/XCoordinator#225]
A `NavigationCoordinator` defined in a Framework, when used in my App, crashes at the following place:

```swift
public var strongRouter: StrongRouter<RouteType> {
  StrongRouter(self) // <-- Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
}
```
I have verified that when all of the exact same code is in the App project, everything works as expected. Do I need any configuration settings to make things work with Frameworks?

**Using**
- XCoordinator - 2.2.0
- Cocoapods - 1.11.2
- Xcode - 13.3

**For context**
I'm trying to modularise my features into separate Frameworks. Each feature Framework must have their own Navigation Coordinator. Everything gets tied up in one App level Navigation Coordinator.

**Comment by pauljohanneskraft** [comment]
Hey @janakagamini - that is a cool way to modularize an app - I like it.

The error in question seems to be that you are creating a StrongRouter from an object that has already been deallocated for some reason, could that be? I found this article, I hope it might help a little with these kinds of errors: https://www.avanderlee.com/swift/exc-bad-access-crash/.

I'm also interested in how the different frameworks are built and linked together - could this be the root of the issue? For example: Is every framework correctly linked to one version of XCoordinator or do they all have their separate version (if that is even possible, I don't know)? And could it be that this is the first ever call to a XCoordinator method from one module to another? I.e. could it be that all XCoordinator methods are called from within module A, while strongRouter is the first call to XCoordinator on an object that was "created" by module B? That would explain, that the issue is that the `StrongRouter` initializer itself could not be found rather than `self` in your code example.

I'm afraid, I cannot think of a way to help you more without some more context though - would you be willing to share some more information for me to look into this? Especially a stack trace or some code that is related to the instantiation of the object in question and how it is referenced at runtime, would be helpful. If you cannot share code publicly, you can also share it in a private message in our Slack workspace (see README on the bottom for an invite link).

**Comment by janakagamini** [comment]
Oh my god, silly mistake on my part, I was missing `use_frameworks!` from my Podfile 🤦 !

Thanks @pauljohanneskraft your response helped point me in the right direction. I am closing this issue.
