### ISSUE TITLE
Problem presenting a modal and using a coordinator as a child

### ISSUE THREAD

**Issue by hugovanderlei** [quickbirdstudios/XCoordinator#243]
I'm having a hard time presenting a modal in a NavigationCoordinator.

The modal is presented inside a navigation controller, when i'm in this modal and a route is triggered using another coordinator as a child, the new screen is pushed behind the presented modal. I believe that happens because the rootViewController sent to the Coordinator used as a child is different from the new one that is presented modally. 

Is there a way to correct that?

**Comment by pauljohanneskraft** [comment]
Hey @hugovanderlei !

Yes, it seems that there is some issue with how the coordinators relate to the view controllers in use. Am I correct in the assumption that you use XCoordinator throughout your whole application? Or do you only use it in a small part of it and this is at the edge of where it is used (as in the initial navigation controller is not in it, but the modal is, for example)?

From your message, I'd assume that you would need a NavigationCoordinator that coordinates the initial UINavigationController and then you would perform a `.present(...)` transition to a new NavigationCoordinator with another UINavigationController.

If I am right in this assumption, then I would assume further that you are currently performing a `.push(...)` transition on that first NavigationCoordinator, right? It should however, be performed on the second one (i.e. the one that coordinates the navigation controller inside that modal).

Could it be that you currently have the misconception that XCoordinator keeps track of what the "current" flow is and automatically triggers transitions on that view controller? If yes, then that is incorrect. It will always (there are some minor exceptions explained in the following) perform them on the rootViewController of the coordinator it is being performed on.

The two exceptions, where a transition is not performed on the rootViewController of the coordinator it is being performed on:

- transitions that simply check for related view controllers from that rootViewController (e.g. `.present(_:)` checks if there are already presented view controllers and presents on top of them instead, since it would otherwise not work in UIKit)
- `.perform(_:on:)`, `.trigger(_:on:)` or `.route(_:on:)` transitions forward a transition or route to another coordinator/view controller

**Comment by hugovanderlei** [comment]
Hello! thanks for your quick response!

I'm using a navigationCoordinator to present modally

<img width="581" alt="Captura de Tela 2023-04-06 às 08 48 41" src="https://user-images.githubusercontent.com/184836/230367813-80d0422e-b3f4-472c-8922-d3b69e5ffce8.png">

In the .addOtherAthlete route there is a trigger that calls .createAthlete

<img width="527" alt="Captura de Tela 2023-04-06 às 08 49 28" src="https://user-images.githubusercontent.com/184836/230368259-74aa7730-2910-461b-a26f-5ff71e27a804.png">

The rootViewController is not updated with the presentedViewController, i managed to fix it by writing an extension that returns the rootViewController. presentedViewController, I'm not sure whether that's correct, but it worked.



<img width="959" alt="Captura de Tela 2023-04-06 às 09 00 08" src="https://user-images.githubusercontent.com/184836/230372931-b011f5ed-e65b-4d68-aef2-ff8c92283cc9.png">

**Comment by pauljohanneskraft** [comment]
Okay, I think I found the issue here:

What you would want to do is encapsulate the behavior of the modal into its own coordinator, rather than having two coordinators (your `NavigationController<EventSubscriptionRoute>` and `AthleteCoordinator`) and injecting the weakRouter of the parent/parent's parent respectively.

May I suggest the following changes:

1. The AddOtherAthleteViewModel gets an `UnownedRouter<AthleteCoordinator.RouteType>`.
2. In the parent coordinator, you return `.present(AthleteCoordinator(...))` instead of a `.present(NavigationCoordinator<EventSubscriptionRoute>(...))`
3. In AthleteCoordinator's initializer, you make sure to create the AddOtherAthleteViewController and AddOtherAthleteViewModel with the reference to its own weakRouter/unownedRouter, e.g. by having an `.initial(...)` route that creates them and uses the `.push` transition that is then used in the initializer as `initialRoute:` parameter.

With these changes, you will make sure that the `AddOtherAthleteViewModel` only knows/controls the modal rather than being coupled to the parent navigation coordinator.

Does this make sense?

**Comment by hugovanderlei** [comment]
Great, thank you! it makes total sense
