### ISSUE TITLE
Error: Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by dillidon** [quickbirdstudios/XCoordinator#59]
In example when press button in Login View appears this error in BaseCoordinator:
``` swift
public var rootViewController: RootViewController {
        // swiftlint:disable:next force_unwrapping
        return rootViewControllerBox.get()!
    }
```

**Comment by pauljohanneskraft** [comment]
Thanks for mentioning! It should be fixed with https://github.com/quickbirdstudios/XCoordinator/pull/60.

**Comment by lexrus** [comment]
<img width="1424" alt="screen shot 2019-01-31 at 11 10 18 pm" src="https://user-images.githubusercontent.com/219689/52063578-de42cb00-25ad-11e9-9b02-3533313bf084.png">

Still got this error while present a navigation coordinator in superCoordinator(a TabBarCoordinator) at the second time.

My code is kind of the same as the code in #25

**Comment by pauljohanneskraft** [comment]
It happens when `presented(from:)` is called on a coordinator but the rootViewController is not really in the view hierarchy and later on it is used again (since it is only held weakly after `presented(from:)`) is called. To really help you with this problem, we will need more information, e.g. which coordinator classes are used, which transitions are used, etc.

**Comment by lexrus** [comment]
Thank you for your reply. I built a demo to showcase this crash.
https://github.com/lexrus/XCoordinatorIssueDemo

**Comment by pauljohanneskraft** [comment]
Hey, so I've taken a look at the project, found the problem and will propose a few possible solutions:

Problem:
You are storing an AnyRouter<AuthRoute> which is (potentially) presented many times during the lifetime of your app. After the router has first been presented, the rootViewController is released and only strongly held by the view hierarchy. When the router is dismissed, the rootViewController is deallocated. When presenting the same router again, the rootViewController cannot be found (since it was deallocated).

Solutions:
1. Hold a strong reference to the rootViewController of the AnyRouter<AuthRoute> as well. This might be a bit crowded in the MainTabCoordinator.

2. Override `presented(from:)` in AuthCoordinator without calling super. In `presented(from:)` a Coordinator releases the strong reference to its rootViewController - Keep in mind, that you might create reference cycles when holding a strong reference to the AuthCoordinator in one of the pushed viewControllers.

3. **Prefered option** Whenever `MainRoute.auth` is triggered, create a new router and save it in the authRouter variable (if necessary) of your MainTabCoordinator.

I hope, I could help with your problem - I understand that this is an inconvenience of the current implementation but as there could be reference cycles when holding the coordinator in one of the pushed viewControllers (e.g. by holding it in a viewModel, as shown in the Example app), we decided to go this path for now - we might change this in the future (possibly by introducing a WeakAnyRouter, which would not hold a strong reference to the coordinator and therefore solve the reference cycles at another point).

**Comment by lexrus** [comment]
Fixed with the 3rd option. Thank you for your reply.
