### ISSUE TITLE
How can I release previous screens?

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#61]
Hello,

I have a problem and I don't really know how to fix it.

Let's say I have a route, OnBoardingRoute, which is a navigation controller with several screens.
Then the last screen, a modal screen is presented (animation from the bottom), called DashboardRoute (or HomeRoute). Using .present(vc)
Once  you are there, there is no possibility to dismiss or go back, that is, now it is a completely independent screen.
Right now, I realised that all the screens presented previously are still on memory, which is normal, because it is a modal view.
How can I release them?

Thanks.

(Is this related with RedirectionRouter/RedirectionCoordinator?)

**Comment by pauljohanneskraft** [comment]
Can you present the OnboardingRoute-VC first and dismiss it later? Then the OnboardingRoute-VC/Coordinator would disappear since it is no longer in the view hierarchy.

I see this more of a UIKit-related problem, since it is normal to hold strongly to viewControllers that are in the view hierarchy. What would your approach be, if you would not use XCoordinator?

Which of your routers/coordinators is a RedirectionRouter/RedirectionCoordinator? Keep in mind, that the superCoordinator's rootViewController needs to stay in the view hierarchy to be able to trigger routes or perform transitions on it.

**Comment by Ricardo1980** [comment]
Thanks for reply!
I don't know anything about RedirectionRouter/RedirectionCoordinator at the moment. Reading about that right now.

My app delegate has this:
```
            onBoardingCoordinator = BasicCoordinator<OnBoardingRoute>(initialRoute: .landing(ualService : UALService()),
                                                                 initialLoadingType: .immediately)
            window.rootViewController = onBoardingCoordinator.rootViewController
```
I guess that is wrong because I should have something like a root coordinator or root. Right?

**Comment by pauljohanneskraft** [comment]
Which version of this pod are you using? Are you still using RxCoordinator (< v1.0) or already XCoordinator (>= v1.0)? 

Please update to the latest version and use `onBoardingCoordinator.setRoot(for: window)`. You do not necessarily need a rootCoordinator since OnboardingCoordinator can be your root coordinator. You should also be able to change that later by calling `otherCoordinator.setRoot(for: window)`.

**Comment by Ricardo1980** [comment]
Thanks!
I am using 
github "dkpoulsen/RxCoordinator" "904adb2fae8f8f89fdc87dd211a00d94abcb09ab"
and I have no idea about the reason (the previous developer left)
I will try to update to the last version.
I see that you renamed the project from RxCoordiantor to XCoordinator. Is that to clarify that there is no dependency with RxSwift?
Regarding your suggestion, "You do not necessarily need a rootCoordinator since OnboardingCoordinator can be your root coordinator. " If I do that, the navigation controller is still on memory (and its view controllers), correct?
I am going to try to implement the second option. Is it a good practice to call setRoot in Rote file?
Thanks a lot for your time and suggestions.

**Comment by Ricardo1980** [comment]
"Yes, the navigationController will still be in memory until it is no longer in the view hierarchy, although this is not an issue of XCoordinator but the regular behavior of UIKit"
I have to remove it because it is opening a web socket. 

"If you are talking about memory leaks, then we strongly advise to update to XCoordinator."
I didn't see that, but I update right now.

"If you are talking about removing coordinators where the viewControllers are still in the view hierarchy, we strongly advise to change the view hierarchy, since you could theoretically (by accident) go back to those viewControllers (e.g. by calling dismiss to the presented viewControllers)."
OK, that's what I want. Thanks  a lot.
