### ISSUE TITLE
Can not find navigationController in rootViewController

### ISSUE THREAD

**Issue by Sky-star** [quickbirdstudios/XCoordinator#75]
![image](https://user-images.githubusercontent.com/6882646/54596233-2b500300-4a6f-11e9-9b92-a01ff8d377bc.png)
I set rootViewController in AppCoordinator, but in rootViewController can not find navigationcontroller

**Comment by pauljohanneskraft** [comment]
Could you please explain the problem or question in more detail? With the given information, we unfortunately cannot help at this point.

**Comment by Sky-star** [comment]
In your demo,i want to hidden navigationbar in loginViewController, it didn't work for me..
![image](https://user-images.githubusercontent.com/6882646/54651109-5dec1100-4aec-11e9-8f2b-7de4a95d7f52.png)

**Comment by pauljohanneskraft** [comment]
The viewController does not yet have a navigationController at the time of loading the view. Since the view is necessary for binding the viewModel (otherwise IBOutlets are nil), we call `loadViewIfNeeded()` before the viewController is pushed onto the navigationController. Move the code into `viewWillAppear` and it should work fine.

**Comment by Sky-star** [comment]
Thank's for you help~
