### ISSUE TITLE
How implemented the PageCoordinator ? 

### ISSUE THREAD

**Issue by Tawfikk** [quickbirdstudios/XCoordinator#77]
I have the root coordinator, HomeTabCoordinator, and this router I set two tabbar items, AboutController and NewsController and created for them coordinate classes.

For NewsCoordinator I have next router:

```
enum NewsListRouter: Route {
    case newsList
    case selectedNews(newsID: Int)
}
```

and I open the NewsDetailViewController next way: 

```
func detailNewsTrigger(_ id: Int) {
        router.trigger(.selectedNews(newsID: id))
    }
```

For this screen I have the next design, buttons for news paging:

<img width="537" alt="Screenshot 2019-03-24 at 01 54 31" src="https://user-images.githubusercontent.com/28268405/54872621-ccc0b700-4dd7-11e9-83f6-88944f1de605.png">

How do I implement the function, when tapped for NextButton, showing next news and also, the previewButton, showing preview news ? 

I know about the PageCoordinator, but no idea how it implemented for my project, although looking at your example HomePageCoordinator. Please, help

**Comment by pauljohanneskraft** [comment]
PageCoordinator seems to be an interesting idea here, although I'd say it would require a custom UIPageViewControllerDelegate in which the next or previous view controllers are loaded (at least, if lazy loading is required, which it probably should).

I'm first of all ignoring data flow, since I don't know how the existing project is set up.

For changing the currently displayed page from the tap of a button use `PageTransition.set(_:direction:)` with the to-be-shown viewController(s) and the direction in which the animation should be shown (just like ´UIPageViewController.setViewControllers`).

If swiping is required/wanted, use the `UIPageViewControllerDelegate` methods in your delegate that you are providing in the initializer to generate viewControllers depending on the swipe direction. (If you are overriding `generateRootViewController` this delegate might not be set though).

**Comment by pauljohanneskraft** [comment]
For a route type with cases `left` and `right`, the following code illustrates a way, where one would only need to implement a `UIPageViewControllerDataSource` and connect the buttons to the respective route cases.

```swift
case .left:
    guard let currentViewController = rootViewController.viewControllers?.first,
        let previousViewController = rootViewController.dataSource?
            .pageViewController(rootViewController, viewControllerBefore: currentViewController) else {
                return .none()
    }
    return .set(previousViewController, direction: .reverse)
case .right:
    guard let currentViewController = rootViewController.viewControllers?.first,
        let nextViewController = rootViewController.dataSource?
            .pageViewController(rootViewController, viewControllerAfter: currentViewController) else {
                return .none()
    }
    return .set(nextViewController, direction: .forward)
```

**Comment by pauljohanneskraft** [comment]
I'm closing this now - if the question / problem persists or there are follow-up questions, feel free to reopen.

**Comment by Tawfikk** [comment]
thanks for the answer!

**Comment by Tawfikk** [comment]
@pauljohanneskraft, I need implement a PageCoordinatorDataSource ? And if so, how I create controller and use the pages stored properties ?

**Comment by Tawfikk** [comment]
It would be cool to see an example with a similar implementation that I brought

**Comment by pauljohanneskraft** [comment]
With the most recent version of XCoordinator, you can also create a PageCoordinator without being constrained to the PageCoordinatorDataSource, but you can instead use any UIPageViewControllerDataSource.

**Comment by Tawfikk** [comment]
In UIPageViewControllerDataSource how add controller to 'pages' stored properties ?

**Comment by pauljohanneskraft** [comment]
In `UIPageViewControllerDataSource` there is no stored property `pages`, this is only the case for our implementation `PageControllerDataSource`. 

Please refer to the UIKit documentation for further questions regarding the `UIPageViewControllerDataSource` protocol.

If you have further questions regarding the XCoordinator framework, feel free to ask, but please keep in mind, that without elaborating on your problem, it is really hard to understand the problem and as a result of that, it is hard to find a solution.
