### ISSUE TITLE
Example App: Shell Script Invocation Error Group

### ISSUE THREAD

**Issue by KylChiang** [quickbirdstudios/XCoordinator#85]
Hi I got this when run XCoordinator-Example:
![image](https://user-images.githubusercontent.com/6602239/57009838-a0e0ee80-6c2b-11e9-959a-f3ddc1549cd2.png)

any idea please?

**Comment by pauljohanneskraft** [comment]
This seems to be related to the SwiftLint build phase. 
Since you happen to have a whitespace in the path of your project, the script does not seem to find the SwiftLint-executable.
To still run the project, either remove the SwiftLint build phase or move the project to a path not containing a whitespace.
